### ISSUE TITLE
fed-ixi dataset download issue

### ISSUE THREAD

**Issue by mvesin** [owkin/FLamby#256] opened 2022-11-14 14:34 UTC
Hi all,

When running `./flamby/datasets/fed_ixi/dataset_creation_scripts/download.py` it fails with

```bash
  File "/myhome/.conda/envs/mycondaenv/lib/python3.9/site-packages/flamby/datasets/fed_ixi/dataset_creation_scripts/download.py", line 47, in dl_ixi_tiny
    response.raise_for_status()
[...]
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://md-datasets-cache-zipfiles-prod.s3.eu-west-1.amazonaws.com/7kd5wj7v7p-1.zip
```

Doesn't the download link need to be updated ?
Thank in advance.

**Comment by jeandut** [comment] 2022-11-14 17:52
Hello, the issue was identified this morning (see #253). We will try to fix it ASAP. Maybe it's just about updating the url with @sharkovsky's link.

**Comment by jeandut** [comment] 2022-11-14 17:53
Closing as duplicate of #253 .

**Closed by jeandut** 2022-11-14 17:53 UTC

**Comment by mvesin** [comment] 2022-11-15 15:32
Great, thanks.
It works for me using the new link.
